Use -isystem to include gtest
This will ignore warning in gtest
since it is not compatible with some of the flags beeing enforced

  gtest.cc:1266:43:
  error: implicit conversion from ‘float’ to ‘double’ to match other
  operand of binary expression [-Werror=double-promotion]
   1266 |         costs[l_i + 1][r_i + 1] = replace + 1.00001;
        |                                   ~~~~~~~~^~~~~~~~~